version: '3'
services:
  mydb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dre123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local
